import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    scrollContent: {
        flexGrow: 1,
    },
    header: {
        height: 120,
        position: 'relative',
    },
    headerGradient: {
        flex: 1,
        backgroundColor: '#667eea',
        paddingVertical: 20,
        paddingHorizontal: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#FFFFFF',
        textAlign: 'center',
        marginBottom: 4,
    },
    headerSubtitle: {
        fontSize: 14,
        color: '#E2E8F0',
        textAlign: 'center',
        opacity: 0.9,
    },
    avatarSection: {
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        paddingVertical: 40,
        paddingHorizontal: 20,
        marginTop: -20,
        marginHorizontal: 16,
        borderRadius: 24,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    avatarContainer: {
        position: 'relative',
        marginBottom: 20,
    },
    avatarGlow: {
        padding: 4,
        borderRadius: 64,
        backgroundColor: '#667eea',
    },
    avatar: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#8B5CF6',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 4,
        borderColor: '#FFFFFF',
    },
    avatarText: {
        fontSize: 42,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    statusIndicator: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 3,
    },
    onlineStatus: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#10B981',
    },
    onlinePulse: {
        position: 'absolute',
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#10B981',
        opacity: 0.3,
    },
    userName: {
        fontSize: 28,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 6,
        textAlign: 'center',
    },
    userHandle: {
        fontSize: 16,
        color: '#6B7280',
        marginBottom: 12,
        textAlign: 'center',
    },
    roleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        marginBottom: 24,
    },
    roleIcon: {
        marginRight: 8,
    },
    userRole: {
        fontSize: 16,
        color: '#8B5CF6',
        fontWeight: '600',
    },
    statsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
        paddingVertical: 16,
        paddingHorizontal: 24,
        borderRadius: 16,
        width: '100%',
    },
    statItem: {
        flex: 1,
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 2,
    },
    statLabel: {
        fontSize: 12,
        color: '#6B7280',
        fontWeight: '500',
    },
    statDivider: {
        width: 1,
        height: 30,
        backgroundColor: '#E5E7EB',
        marginHorizontal: 16,
    },
    contactSection: {
        marginTop: 24,
        paddingHorizontal: 16,
        paddingBottom: 20,
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 6,
        textAlign: 'center',
    },
    sectionSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 24,
    },
    contactList: {
        gap: 12,
    },
    contactItem: {
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    selectedItem: {
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
    },
    contactTouchable: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
    },
    iconContainer: {
        width: 44,
        height: 44,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    contactInfo: {
        flex: 1,
    },
    contactLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    contactValue: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '400',
    },
});

export default styles;